### ISSUE TITLE
请教下：动态加密的接口，如何处理？

### ISSUE THREAD

**Issue by testerwang11** [asura-pro/indigo-api#6]
场景：每个接口请求都会带个sign参数，是根据其他参数的值计算出来的。参数发生变化，这个sign也会变。
目前：想在发送请求前，计算出sgin,去替换掉参数里边的seq。
请教下，替换参数这一步要在哪里修改？非常感谢

**Comment by xcorpio** [comment]
可以看下这里， https://docs.asura.pro/#/zh-cn/plugins
